"""Constants for Abaqus job statuses, file extensions, and known keywords."""

from __future__ import annotations

# ── Job status strings ───────────────────────────────────────────────────────

JOB_COMPLETED = "completed"
JOB_RUNNING = "running"
JOB_FAILED = "failed"
JOB_ABORTED = "aborted"
JOB_SUBMITTED = "submitted"
JOB_UNKNOWN = "unknown"

# ── File extensions generated by Abaqus ──────────────────────────────────────

KNOWN_EXTENSIONS: set[str] = {
    ".inp",
    ".odb",
    ".cae",
    ".jnl",
    ".sta",
    ".msg",
    ".dat",
    ".log",
    ".com",
    ".prt",
    ".sim",
    ".mdl",
    ".stt",
    ".lck",
    ".023",
    ".cid",
    ".pac",
    ".abq",
    ".res",
    ".sel",
    ".fct",
    ".sup",
    ".par",
    ".pmg",
    ".ipm",
    ".lck",
    ".env",
}

# Extensions safe to delete during cleanup (intermediate / regenerable files)
CLEANABLE_EXTENSIONS: set[str] = {
    ".com",
    ".prt",
    ".sim",
    ".mdl",
    ".stt",
    ".023",
    ".cid",
    ".pac",
    ".abq",
    ".res",
    ".sel",
    ".lck",
    ".log",
    ".sta",
    ".msg",
    ".dat",
}

# ── Log keywords for automatic diagnosis ─────────────────────────────────────

ERROR_KEYWORDS: list[str] = [
    "ERROR",
    "***ERROR",
    "THE ANALYSIS HAS NOT BEEN COMPLETED",
    "TOO MANY ATTEMPTS MADE",
    "TOO MANY INCREMENTS NEEDED",
    "TIME INCREMENT REQUIRED IS LESS THAN",
    "NUMERICAL SINGULARITY",
    "ZERO PIVOT",
    "NEGATIVE EIGENVALUE",
    "EXCESSIVE DISTORTION",
    "CONTACT PAIR",
    "SEVERE DISCONTINUITY",
    "FORCE EQUILIBRIUM NOT ACHIEVED",
    "CONVERGENCE NOT ACHIEVED",
]

WARNING_KEYWORDS: list[str] = [
    "WARNING",
    "***WARNING",
    "DISTORTED",
    "UNCONVERGED",
    "NUMERICAL SINGULARITY",
    "CONTACT PAIR",
]

SUCCESS_KEYWORDS: list[str] = [
    "THE ANALYSIS HAS COMPLETED SUCCESSFULLY",
]
