"""Clean up intermediate files generated by an Abaqus job."""

from __future__ import annotations

import logging
from pathlib import Path

from abaqus_mcp_server.abaqus_cli import AbaqusCLI
from abaqus_mcp_server.app import mcp
from abaqus_mcp_server.config import AbaqusServerConfig
from abaqus_mcp_server.security import validate_filename

logger = logging.getLogger(__name__)


@mcp.tool(
    name="clean_job",
    description="Remove intermediate files generated by an Abaqus job "
    "(.com, .prt, .sim, .mdl, .stt, .023, .lck, etc.). "
    "IMPORTANT: This deletes files and MUST be confirmed by the user. "
    "Set confirmed=True to proceed. "
    "The .odb, .inp, and .cae files are never deleted.",
)
async def clean_job(
    job_name: str,
    confirmed: bool = False,
) -> str:
    """Delete intermediate files for a job.

    Args:
        job_name: Name of the job (without extension).
        confirmed: Must be True to actually delete files.
    """
    if not confirmed:
        return (
            "⚠️  File deletion requires confirmation. "
            "Please call this tool again with confirmed=True to proceed.\n\n"
            f"Job name: {job_name}\n\n"
            "This will delete intermediate files (.com, .prt, .sim, .msg, .dat, .sta, .log, etc.) "
            "but will keep .odb, .inp, and .cae files."
        )

    cfg = AbaqusServerConfig()

    try:
        validate_filename(job_name)
    except Exception as exc:
        return f"Error: Invalid job name: {exc}"

    ws = cfg.resolve_workspace()
    cli = AbaqusCLI(cfg)

    # Search jobs dir, then root
    search_dirs = [ws / "jobs", ws]
    deleted: list[str] = []
    errors: list[str] = []

    for d in search_dirs:
        # Check if job is running
        lck = d / f"{job_name}.lck"
        if lck.exists():
            return f"Error: Job '{job_name}' appears to be running (.lck exists). Cannot clean."

        try:
            removed = await cli.clean_job(job_name, cwd=d)
            deleted.extend(str(f.name) for f in removed)
        except Exception as exc:
            errors.append(str(exc))

    lines = [f"=== Cleaned Job: {job_name} ==="]
    if deleted:
        lines.append(f"Deleted {len(deleted)} file(s):")
        for name in sorted(deleted):
            lines.append(f"  - {name}")
    else:
        lines.append("No intermediate files found to delete.")

    if errors:
        lines.append(f"\nErrors ({len(errors)}):")
        for e in errors:
            lines.append(f"  - {e}")

    return "\n".join(lines)
