"""Generate ready-to-run Abaqus Python scripts from descriptions."""

from __future__ import annotations

import logging
from pathlib import Path

from abaqus_mcp_server.app import mcp
from abaqus_mcp_server.config import AbaqusServerConfig
from abaqus_mcp_server.security import validate_filename, validate_path

logger = logging.getLogger(__name__)


@mcp.tool(
    name="generate_script",
    description="Generate an Abaqus Python script for common modeling tasks. "
    "Returns a ready-to-run Python script that can be saved and executed "
    "via the run_script tool. Supports: static_analysis, modal_analysis, "
    "contact_analysis, and cantilever_beam.",
)
async def generate_script(
    task: str,
    model_name: str,
    output_script: str,
    parameters: str = "{}",
) -> str:
    """Generate an Abaqus Python modeling script.

    Args:
        task: Type of analysis (static_analysis, modal_analysis, contact_analysis, cantilever_beam).
        model_name: Name for the Abaqus model.
        output_script: Path to write the generated script (relative to workspace).
        parameters: JSON dict of model parameters (e.g., length, width, height, force).
    """
    import json as _json

    cfg = AbaqusServerConfig()
    ws = cfg.resolve_workspace()

    try:
        params = _json.loads(parameters)
    except _json.JSONDecodeError as exc:
        return f"Error: Invalid JSON parameters: {exc}"

    # Validate output path
    try:
        output = validate_path(output_script, workspace=ws)
    except Exception as exc:
        return f"Error: Invalid output path: {exc}"

    if output.suffix.lower() not in (".py",):
        return "Error: output_script must have a .py extension."

    # Generate based on task type
    gen_fns = {
        "cantilever_beam": _generate_cantilever,
        "static_analysis": _generate_static,
        "modal_analysis": _generate_modal,
        "contact_analysis": _generate_contact,
    }

    if task not in gen_fns:
        return f"Error: Unknown task '{task}'. Available: {', '.join(gen_fns.keys())}"

    script = gen_fns[task](model_name, params)

    # Write the script
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(script, encoding="utf-8")

    lines = [
        f"=== Script Generated ===",
        f"Task: {task}",
        f"Model: {model_name}",
        f"Saved to: {output}",
        f"",
        f"To run this script: run_script(script_path='{output_script}')",
        f"",
        f"--- Script preview (first 50 lines) ---",
    ]
    preview = script.splitlines()[:50]
    lines.extend(preview)

    return "\n".join(lines)


# ── Template generators ──────────────────────────────────────────────────────


def _generate_cantilever(name: str, p: dict) -> str:
    L = p.get("length", 100)
    W = p.get("width", 10)
    H = p.get("height", 10)
    F = p.get("force", 1000)
    E = p.get("youngs_modulus", 210000)
    nu = p.get("poissons_ratio", 0.3)
    mesh_size = p.get("mesh_size", 5)

    return f'''"""Cantilever beam static analysis — generated by Abaqus MCP Server."""

from abaqus import *
from abaqusConstants import *

# Create model
Mdb()
model = mdb.Model(name="{name}")
if "Model-1" in mdb.models:
    del mdb.models["Model-1"]

# Create part
s = model.ConstrainedSketch(name="beam_profile", sheetSize=200.0)
s.rectangle(point1=(0.0, 0.0), point2=({L}, {H}))
beam = model.Part(name="Beam", dimensionality=THREE_D, type=DEFORMABLE_BODY)
beam.BaseSolidExtrude(sketch=s, depth={W})

# Material
mat = model.Material(name="Steel")
mat.Elastic(table=(({E}, {nu}),))

# Section
model.HomogeneousSolidSection(name="BeamSection", material="Steel")
region = beam.Set(cells=beam.cells.findAt(((0, 0, 0),)), name="AllCells")
beam.SectionAssignment(region=region, sectionName="BeamSection")

# Assembly
ass = model.rootAssembly
inst = ass.Instance(name="Beam-1", part=beam, dependent=ON)

# Step
model.StaticStep(name="Step-1", previous="Initial", nlgeom=OFF,
    initialInc=0.1, maxInc=0.1, minInc=1e-05)

# Boundary condition — fixed end
fixed_faces = inst.faces.findAt(((0, {H/2}, {W/2}),))
fixed_region = inst.Set(faces=fixed_faces, name="FixedEnd")
model.EncastreBC(name="FixedEnd", createStepName="Initial", region=fixed_region)

# Load — point force at free end
load_face = inst.faces.findAt((({L}, {H/2}, {W/2}),))
load_region = inst.Set(faces=load_face, name="LoadedEnd")
model.Pressure(name="TipLoad", createStepName="Step-1",
    region=load_region, magnitude={F/(W*H)})

# Mesh
elem_type = mesh.ElemType(elemCode=C3D8R)
beam.setElementType(regions=(beam.cells,), elemTypes=(elem_type,))
beam.seedPart(size={mesh_size})
beam.generateMesh()

# Job
job = mdb.Job(name="{name}", model="{name}")
job.writeInput()
print("Job {name} input file written.")
'''


def _generate_static(name: str, p: dict) -> str:
    return _generate_cantilever(name, p)  # Alias for now


def _generate_modal(name: str, p: dict) -> str:
    L = p.get("length", 100)
    W = p.get("width", 10)
    H = p.get("height", 10)
    E = p.get("youngs_modulus", 210000)
    nu = p.get("poissons_ratio", 0.3)
    num_modes = p.get("num_modes", 10)

    return f'''"""Modal analysis — generated by Abaqus MCP Server."""

from abaqus import *
from abaqusConstants import *

Mdb()
model = mdb.Model(name="{name}")
if "Model-1" in mdb.models:
    del mdb.models["Model-1"]

# Geometry
s = model.ConstrainedSketch(name="profile", sheetSize=200.0)
s.rectangle(point1=(0.0, 0.0), point2=({L}, {H}))
beam = model.Part(name="Beam", dimensionality=THREE_D, type=DEFORMABLE_BODY)
beam.BaseSolidExtrude(sketch=s, depth={W})

# Material
mat = model.Material(name="Steel")
mat.Elastic(table=(({E}, {nu}),))
mat.Density(table=((7.85e-09,),))  # 7850 kg/m^3 in tonne/mm^3

model.HomogeneousSolidSection(name="BeamSection", material="Steel")
beam.SectionAssignment(
    region=beam.Set(cells=beam.cells.findAt(((0, 0, 0),)), name="AllCells"),
    sectionName="BeamSection")

ass = model.rootAssembly
inst = ass.Instance(name="Beam-1", part=beam, dependent=ON)

# Frequency step
model.FrequencyStep(name="Step-1", previous="Initial",
    numEigen={num_modes}, eigensolver=LANCZOS)

# Fixed end
fixed = inst.Set(faces=inst.faces.findAt(((0, {H/2}, {W/2}),)), name="Fixed")
model.EncastreBC(name="Fixed", createStepName="Initial", region=fixed)

# Mesh
elem_type = mesh.ElemType(elemCode=C3D8R)
beam.setElementType(regions=(beam.cells,), elemTypes=(elem_type,))
beam.seedPart(size={p.get("mesh_size", 5)})
beam.generateMesh()

job = mdb.Job(name="{name}", model="{name}")
job.writeInput()
print("Job {name} input file written.")
'''


def _generate_contact(name: str, p: dict) -> str:
    return f'''"""Contact analysis template — generated by Abaqus MCP Server.

This is a template; modify geometry, materials, and contact properties
to match your specific model.
"""
from abaqus import *
from abaqusConstants import *

Mdb()
model = mdb.Model(name="{name}")
if "Model-1" in mdb.models:
    del mdb.models["Model-1"]

# Create two parts in contact
# Part 1: Base
s1 = model.ConstrainedSketch(name="base_sketch", sheetSize=200.0)
s1.rectangle(point1=(0.0, 0.0), point2=(100, 20))
base = model.Part(name="Base", dimensionality=THREE_D, type=DEFORMABLE_BODY)
base.BaseSolidExtrude(sketch=s1, depth=100)

# Part 2: Punch
s2 = model.ConstrainedSketch(name="punch_sketch", sheetSize=200.0)
s2.rectangle(point1=(40, 20), point2=(60, 40))
punch = model.Part(name="Punch", dimensionality=THREE_D, type=DEFORMABLE_BODY)
punch.BaseSolidExtrude(sketch=s2, depth=100)

# Materials
steel = model.Material(name="Steel")
steel.Elastic(table=((210000, 0.3),))
model.HomogeneousSolidSection(name="SolidSection", material="Steel")

for part_name in ["Base", "Punch"]:
    p = model.parts[part_name]
    p.SectionAssignment(
        region=p.Set(cells=p.cells.findAt(((0, 0, 0),)), name="All"),
        sectionName="SolidSection")

# Assembly
ass = model.rootAssembly
base_inst = ass.Instance(name="Base-1", part=base, dependent=ON)
punch_inst = ass.Instance(name="Punch-1", part=punch, dependent=ON)

# Contact pair
model.SurfaceToSurfaceContactExp(name="Contact",
    master=base_inst.faces.findAt(((50, 20, 50),)),
    slave=punch_inst.faces.findAt(((50, 20, 50),)),
    sliding=FINITE)
model.interactions["Contact"].includedStepPairs = (("Step-1",),)

# Step
model.StaticStep(name="Step-1", previous="Initial",
    initialInc=0.01, maxInc=0.1, minInc=1e-08)

# BCs: fix base bottom, push punch down
base_bot = base_inst.Set(
    faces=base_inst.faces.findAt(((50, 0, 50),)), name="BaseBottom")
model.DisplacementBC(name="FixBase", createStepName="Initial",
    region=base_bot, u1=0.0, u2=0.0, u3=0.0)

punch_top = punch_inst.Set(
    faces=punch_inst.faces.findAt(((50, 40, 50),)), name="PunchTop")
model.DisplacementBC(name="PushDown", createStepName="Step-1",
    region=punch_top, u2=-5.0)

# Mesh
for part in [base, punch]:
    elem_type = mesh.ElemType(elemCode=C3D8R)
    part.setElementType(regions=(part.cells,), elemTypes=(elem_type,))
    part.seedPart(size=5)
    part.generateMesh()

job = mdb.Job(name="{name}", model="{name}")
job.writeInput()
print("Job {name} input file written.")
'''
